sudo: required
services:
  - docker

before_install:
  - docker build -t ZaidTahseen/Docker-Deployment-Nginx-Aws -f Dockerfile.dev .

script:
  - docker run -e CI=true ZaidTahseen/Docker-Deployment-Nginx-Aws npm run test